### ISSUE TITLE
issue in installation

### ISSUE THREAD

**Issue by litonmajumdar** [pkgw/conda-recipes#10]
Hello, 

I am trying to install casa.md in the new mac catalina and I used 

**conda install casa-data casa-python pwkit**

Before I also followed other steps. Could you please help me out understand the issue listed below?

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                       

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - casa-python -> python[version='2.7.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']
  - pwkit -> python[version='2.7.*|3.5.*|3.6.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package numpy-base conflicts for:
pwkit -> numpy -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|>=1.9.3,<2.0a0|1.17.0|1.17.0',build='py37h9797aa9_6|py36h9797aa9_6|py37ha9ae307_6|py35h9797aa9_7|py36h9797aa9_7|py27ha9ae307_7|py27h9797aa9_7|py36h9797aa9_7|py27ha9ae307_7|py36ha9ae307_7|py27ha9ae307_8|py36ha9ae307_8|py36h9797aa9_8|py37ha9ae307_8|py37he97cb71_9|py37h8a80b8c_9|py27h8a80b8c_9|py27he97cb71_9|py35he97cb71_9|py37h42e5f7b_10|py27h42e5f7b_10|py36h8a80b8c_10|py35h42e5f7b_10|py27h8a80b8c_10|py37h8a80b8c_10|py37ha711998_10|py36ha711998_10|py37h6575580_11|py27h6575580_11|py27h6575580_12|py27ha711998_12|py37h6575580_12|py38ha711998_13|py38h6575580_13|py38ha711998_14|py38h6575580_14|py38ha711998_15|py36h7ef55bc_1|py36h479e554_1|py35h479e554_1|py35h7ef55bc_1|py35h9797aa9_0|py27ha9ae307_0|py36ha9ae307_0|py27h9797aa9_0|py27ha9ae307_0|py35h9797aa9_0|py27h9797aa9_1|py36h9797aa9_1|py37ha9ae307_1|py36ha9ae307_1|py36ha9ae307_2|py37ha9ae307_2|py36ha9ae307_3|py27ha9ae307_3|py37ha9ae307_3|py27ha9ae307_4|py36ha9ae307_4|py37ha9ae307_4|py37h9797aa9_4|py35h9797aa9_4|py36ha711998_4|py35h8a80b8c_4|py27ha711998_4|py38h6575580_4|py27h6575580_5|py37ha711998_5|py37h6575580_5|py27h8a80b8c_0|py35he97cb71_0|py37h42e5f7b_0|py35h42e5f7b_0|py36h42e5f7b_0|py27h8a80b8c_0|py36ha711998_0|py35ha711998_0|py37ha711998_0|py27h8a80b8c_0|py27ha711998_1|py36ha711998_1|py27h8a80b8c_1|py36h8a80b8c_1|py37h8a80b8c_1|py37ha711998_0|py27h8a80b8c_0|py27h8a80b8c_0|py37h6575580_0|py27h6575580_0|py27ha711998_0|py37h6575580_0|py37ha711998_0|py27h6575580_0|py27ha711998_1|py36ha711998_1|py37ha711998_1|py36h6575580_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py37h6575580_0|py37ha711998_0|py27h6575580_0|py27h6575580_0|py37h6575580_0|py37ha711998_0|py36h6575580_0|py27h6575580_0|py37h6575580_0|py36h6575580_0|py37h6575580_0|py27h6575580_0|py36h68fea81_0|py38h68fea81_0|py37h68fea81_0|py38hcfb5961_0|py36hcfb5961_0|py37hcfb5961_0|py27ha711998_0|py38ha711998_0|py38h6575580_0|py36ha711998_0|py37ha711998_0|py27ha711998_0|py36ha711998_0|py36h6575580_0|py27ha711998_0|py37ha711998_0|py36ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_1|py37ha711998_1|py27ha711998_1|py37h6575580_1|py27h6575580_1|py36h6575580_0|py27ha711998_0|py36ha711998_0|py27h6575580_1|py37h6575580_1|py36h6575580_0|py36ha711998_0|py36h6575580_0|py37ha711998_0|py36ha711998_0|py27ha711998_0|py36h8a80b8c_0|py37h8a80b8c_0|py36h8a80b8c_0|py36ha711998_0|py27ha711998_0|py37h8a80b8c_0|py37ha711998_1|py35ha711998_0|py36ha711998_0|py36h8a80b8c_0|py35h8a80b8c_0|py37h8a80b8c_0|py27ha711998_0|py37ha711998_0|py27ha711998_0|py35h8a80b8c_0|py37h8a80b8c_0|py27h42e5f7b_0|py36h8a80b8c_0|py35h8a80b8c_0|py36he97cb71_0|py37he97cb71_0|py36h8a80b8c_0|py37h8a80b8c_0|py27he97cb71_0|py36h6575580_5|py27ha711998_5|py36ha711998_5|py38ha711998_4|py27h8a80b8c_4|py36h8a80b8c_4|py37h8a80b8c_4|py37ha711998_4|py35ha711998_4|py35ha9ae307_4|py36h9797aa9_4|py27h9797aa9_4|py37h9797aa9_3|py36h9797aa9_3|py27h9797aa9_3|py27ha9ae307_2|py27h9797aa9_2|py36h9797aa9_2|py37h9797aa9_2|py27ha9ae307_1|py37h9797aa9_1|py35ha9ae307_0|py36h9797aa9_0|py36ha9ae307_0|py35ha9ae307_0|py36h9797aa9_0|py27h9797aa9_0|py27h7ef55bc_1|py27h479e554_1|py38h6575580_15|py38h6575580_12|py38ha711998_12|py36ha711998_12|py37ha711998_12|py36h6575580_12|py36h6575580_11|py36ha711998_11|py27ha711998_11|py37ha711998_11|py35ha711998_10|py27ha711998_10|py36h42e5f7b_10|py35h8a80b8c_10|py36he97cb71_9|py35h8a80b8c_9|py36h8a80b8c_9|py35ha9ae307_8|py35h9797aa9_8|py37h9797aa9_8|py27h9797aa9_8|py37ha9ae307_7|py37h9797aa9_7|py27h9797aa9_7|py36ha9ae307_7|py35ha9ae307_7|py37ha9ae307_7|py37h9797aa9_7|py36ha9ae307_6|py27ha9ae307_6|py27h9797aa9_6|py36h6575580_0|py36ha711998_0']
casa-python -> numpy[version='>=1.9.3,<2.0a0'] -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|>=1.9.3,<2.0a0|1.17.0|1.17.0',build='py37h9797aa9_6|py36h9797aa9_6|py37ha9ae307_6|py35h9797aa9_7|py36h9797aa9_7|py27ha9ae307_7|py27h9797aa9_7|py36h9797aa9_7|py27ha9ae307_7|py36ha9ae307_7|py27ha9ae307_8|py36ha9ae307_8|py36h9797aa9_8|py37ha9ae307_8|py37he97cb71_9|py37h8a80b8c_9|py27h8a80b8c_9|py27he97cb71_9|py35he97cb71_9|py37h42e5f7b_10|py27h42e5f7b_10|py36h8a80b8c_10|py35h42e5f7b_10|py27h8a80b8c_10|py37h8a80b8c_10|py37ha711998_10|py36ha711998_10|py37h6575580_11|py27h6575580_11|py27h6575580_12|py27ha711998_12|py37h6575580_12|py38ha711998_13|py38h6575580_13|py38ha711998_14|py38h6575580_14|py38ha711998_15|py36h7ef55bc_1|py36h479e554_1|py35h479e554_1|py35h7ef55bc_1|py35h9797aa9_0|py27ha9ae307_0|py36ha9ae307_0|py27h9797aa9_0|py27ha9ae307_0|py35h9797aa9_0|py27h9797aa9_1|py36h9797aa9_1|py37ha9ae307_1|py36ha9ae307_1|py36ha9ae307_2|py37ha9ae307_2|py36ha9ae307_3|py27ha9ae307_3|py37ha9ae307_3|py27ha9ae307_4|py36ha9ae307_4|py37ha9ae307_4|py37h9797aa9_4|py35h9797aa9_4|py36ha711998_4|py35h8a80b8c_4|py27ha711998_4|py38h6575580_4|py27h6575580_5|py37ha711998_5|py37h6575580_5|py27h8a80b8c_0|py35he97cb71_0|py37h42e5f7b_0|py35h42e5f7b_0|py36h42e5f7b_0|py27h8a80b8c_0|py36ha711998_0|py35ha711998_0|py37ha711998_0|py27h8a80b8c_0|py27ha711998_1|py36ha711998_1|py27h8a80b8c_1|py36h8a80b8c_1|py37h8a80b8c_1|py37ha711998_0|py27h8a80b8c_0|py27h8a80b8c_0|py37h6575580_0|py27h6575580_0|py27ha711998_0|py37h6575580_0|py37ha711998_0|py27h6575580_0|py27ha711998_1|py36ha711998_1|py37ha711998_1|py36h6575580_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py37h6575580_0|py37ha711998_0|py27h6575580_0|py27h6575580_0|py37h6575580_0|py37ha711998_0|py36h6575580_0|py27h6575580_0|py37h6575580_0|py36h6575580_0|py37h6575580_0|py27h6575580_0|py36h68fea81_0|py38h68fea81_0|py37h68fea81_0|py38hcfb5961_0|py36hcfb5961_0|py37hcfb5961_0|py27ha711998_0|py38ha711998_0|py38h6575580_0|py36ha711998_0|py37ha711998_0|py27ha711998_0|py36ha711998_0|py36h6575580_0|py27ha711998_0|py37ha711998_0|py36ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_1|py37ha711998_1|py27ha711998_1|py37h6575580_1|py27h6575580_1|py36h6575580_0|py27ha711998_0|py36ha711998_0|py27h6575580_1|py37h6575580_1|py36h6575580_0|py36ha711998_0|py36h6575580_0|py37ha711998_0|py36ha711998_0|py27ha711998_0|py36h8a80b8c_0|py37h8a80b8c_0|py36h8a80b8c_0|py36ha711998_0|py27ha711998_0|py37h8a80b8c_0|py37ha711998_1|py35ha711998_0|py36ha711998_0|py36h8a80b8c_0|py35h8a80b8c_0|py37h8a80b8c_0|py27ha711998_0|py37ha711998_0|py27ha711998_0|py35h8a80b8c_0|py37h8a80b8c_0|py27h42e5f7b_0|py36h8a80b8c_0|py35h8a80b8c_0|py36he97cb71_0|py37he97cb71_0|py36h8a80b8c_0|py37h8a80b8c_0|py27he97cb71_0|py36h6575580_5|py27ha711998_5|py36ha711998_5|py38ha711998_4|py27h8a80b8c_4|py36h8a80b8c_4|py37h8a80b8c_4|py37ha711998_4|py35ha711998_4|py35ha9ae307_4|py36h9797aa9_4|py27h9797aa9_4|py37h9797aa9_3|py36h9797aa9_3|py27h9797aa9_3|py27ha9ae307_2|py27h9797aa9_2|py36h9797aa9_2|py37h9797aa9_2|py27ha9ae307_1|py37h9797aa9_1|py35ha9ae307_0|py36h9797aa9_0|py36ha9ae307_0|py35ha9ae307_0|py36h9797aa9_0|py27h9797aa9_0|py27h7ef55bc_1|py27h479e554_1|py38h6575580_15|py38h6575580_12|py38ha711998_12|py36ha711998_12|py37ha711998_12|py36h6575580_12|py36h6575580_11|py36ha711998_11|py27ha711998_11|py37ha711998_11|py35ha711998_10|py27ha711998_10|py36h42e5f7b_10|py35h8a80b8c_10|py36he97cb71_9|py35h8a80b8c_9|py36h8a80b8c_9|py35ha9ae307_8|py35h9797aa9_8|py37h9797aa9_8|py27h9797aa9_8|py37ha9ae307_7|py37h9797aa9_7|py27h9797aa9_7|py36ha9ae307_7|py35ha9ae307_7|py37ha9ae307_7|py37h9797aa9_7|py36ha9ae307_6|py27ha9ae307_6|py27h9797aa9_6|py36h6575580_0|py36ha711998_0']

Package libcxxabi conflicts for:
python=3.8 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|2|3|4|0|hcfea43d_1']
casa-python -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|1|2|3|4|0|hcfea43d_1']

**Comment by pkgw** [comment]
Thanks for inquiring. The issue here is that I need to produce a new set of builds and start targeting Python 3.8.

This might be a bit tricky since, in order to stay compatible with the Python stack, I'll need to start using a newer version of the casacore library, and that sometimes causes build problems.

**Comment by pkgw** [comment]
@litonmajumdar I've uploaded new builds supporting Python 3.8 and CASA 5.6.3. Please give them a try if you have chance.

**Comment by litonmajumdar** [comment]
@pkgw Thanks Peter. It worked.

**Comment by pkgw** [comment]
Great! I will close this issue then.
