### ISSUE TITLE
import casac

### ISSUE THREAD

**Issue by mumoisaac** [pkgw/conda-recipes#11]
hello,

I have been trying to use 'import casac' in my work and it always shows error 'no module named casac'
I have tried to follow your instructions on the link [here](https://github.com/pkgw/conda-recipes/blob/master/CASA.md#reporting-problems). I will appreciate help! I am using casa 6.
regards,
Isaac

**Comment by pkgw** [comment]
Hi Isaac,

I'm afraid that my system doesn't (yet) support CASA 6. You'll have to consult the official NRAO documentation for help on how load it up in a Python environment — I believe that the overall approach is quite different from the way that my CASA 5 tools work.

As such, I'm going to close this issue.

Cheers,

Peter
