### ISSUE TITLE
Segmentation Fault on RHEL 6.2 when importing casac

### ISSUE THREAD

**Issue by pandearti** [pkgw/conda-recipes#3]
Hi,
While using casa-data and casa-python conda packages(from channel pkgw) in our project we are facing various issues with them.
It would be really helpful if you could give your inputs on the below mentioned issues :

1). Segmentation Fault (core dumped)
The issue occurs at various places in the casa-core library below are the details about it :

 a). While importing casac on RHEL 6.2
platform	python version	anaconda2 version	conda-channel	casa-data	casa-nrao-casacore	casa-python	casa-tools
RHEL 6.2	Python2.7	4.3.14	pkgw	r10915	4.6.0	4.6.0	4.6.0

We used pdb for debugging and identified below line in __casac__/atmosphere.py is the cause of error :
importlib.import_module(mname)   [ Line 22]
![image 1](https://cloud.githubusercontent.com/assets/9341123/26371952/f37c7a3c-4019-11e7-95ed-783cae28b729.png)

![image 2](https://cloud.githubusercontent.com/assets/9341123/26372012/232e7f0a-401a-11e7-8940-1ac299b6a4c4.png)

Same issue is intermittent with line 63 (import builtins as __builtin__) in atmosphere.py

This issue is non-reproducible on OSX 10.11, Centos 6.2, Centos 7.3 and RHEL 7.3.

 b). While calling scansforfield method
platform	python version	anaconda2 version	conda-channel	casa-data	casa-nrao-casacore	casa-python	casa-tools
OSX 10.11	Python2.7	4.3.16	pkgw	r10774	4.5	4.6.0	4.5

The scansforfield method on ms metadata also throws segmentation fault error intermittently
      >  anaconda2/lib/python2.7/site-packages/__casac__/msmetadata.py(2134)scansforfield()
      >  return _msmetadata.msmetadata_scansforfield(self, *args, **kwargs)

2).  Intermittent RunTimeError in scansforfield and timesforscan of ms metadata

platform	python version	anaconda2 version	conda-channel	casa-data	casa-nrao-casacore	casa-python	casa-tools
OSX 10.11	Python2.7	4.3.16	pkgw	r10774	4.5	4.6.0	4.5
OSX 10.10	Python2.7	4.2.13	pkgw	r10774	4.5	4.6.0	4.5

 The scansforfield method on ms metadata throws RunTime exception intermittently, below is the screenshot of that
![image](https://cloud.githubusercontent.com/assets/9341123/26371817/89820340-4019-11e7-8810-6b42fb875830.png)

Interestingly the fieldnames method on ms metadata gives names of all the fields present 
![image3](https://cloud.githubusercontent.com/assets/9341123/26372230/cebf1316-401a-11e7-9636-fe4b3c00af4f.png)

Please let us know if you have come across the similar issue, any insights from you will help us to progress.

Thanks,
Arti

**Comment by pkgw** [comment]
OK. It seems to me that there are two separate issues here. I have opened a separate issue for the second problem, [#4](https://github.com/pkgw/conda-recipes/issues/4), regarding the RuntimeErrors from `scansforfield`. For this bug we will focus on the first issue, with the segfaults.

**Comment by pkgw** [comment]
And actually, now that I look more closely, problem (1b) also seems to be something that should be looked at separately since it affects a different operating system. I've copied that information into issue [#5](https://github.com/pkgw/conda-recipes/issues/5).

**Comment by pkgw** [comment]
That means that then *this* issue is isolated to the following problem: a segfault upon the import of the `_atmosphere` module on RHEL 6.2. Not reproducible on OSX 10.11, Centos 6.2, Centos 7.3 and RHEL 7.3.

The `_atmosphere` module is the first binary module that's imported when the binary `casac` Python modules are loaded, so this bug probably indicates a basic problem in the binary code that backs the `casa-python` layer.

First of all, your email said that you had switched to using the `conda-forge` and `pkgw-forge` sets of packages rather than the outdated `pkgw` packages. But the version information in this bug report seems to refer to the old versions. Can you please reply with the versions that you're testing now? The latest available ones should be something like `casacore = 2.2.0_1`, `casa-tools = 4.7.2_1`, and `casa-python = 4.7.2_np112py27_4`, where the piece after the underscore is the "build number" reported by the `conda list` command.

**Comment by pkgw** [comment]
Oops, pressed the wrong button there.

**Comment by pandearti** [comment]
Here are the new package versions (as displayed by conda list command)
Yes we still have same issue with these new packages.

casa-data                 r11000                        0    pkgw-forge
casa-python             4.7.2        np112py27_3    pkgw-forge
casa-tools                4.7.2                            1    pkgw-forge
casacore                  2.2.0                            0    conda-forge

**Comment by pandearti** [comment]
The problem seems to be due to unix system settings.

It is resolved after fixing following:

- Concurrent open file descriptors limit increased to 2048.
- Stack and core limits changed to unlimited.

**Comment by pkgw** [comment]
That is very strange! Sorry I couldn't help you diagnose the problem, but I'm glad you found a solution.
